### ISSUE TITLE
upgrade from 2_4_8-5 to 3_1_2-4 failed

### ISSUE THREAD

**Issue by rafaelmr2** [pkp/docker-ojs#331]
Hi, I'm trying to upgrade from version 2_4_8-5 to 3_1_2-4. When I tried to run "docker exec -ti ojs /usr/local/bin/ojs-upgrade", I got:

```
[OJS Upgrade] Changing to installed off
sed: can't move '/var/www/html/config.inc.phpKpPoLA' to '/var/www/html/config.inc.php': Resource busy
[OJS Upgrade] Upgrading...
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php:456
Stack trace:
#0 /var/www/html/lib/pkp/lib/adodb/adodb.inc.php(558): ADODB_mysql->_connect('10.199.33.18', 'revistas', 'xxx...', 'revistas')
#1 /var/www/html/lib/pkp/classes/db/DBConnection.inc.php(162): ADOConnection->Connect('10.199.33.18', 'revistas', 'xxx...', 'revistas', false)
#2 /var/www/html/lib/pkp/classes/db/DBConnection.inc.php(137): DBConnection->connect()
#3 /var/www/html/lib/pkp/classes/db/DBConnection.inc.php(94): DBConnection->initConn()
#4 /var/www/html/lib/pkp/classes/db/DBConnection.inc.php(53): DBConnection->initDefaultDBConnection()
#5 /var/www/html/lib/pkp/classes/db/DBConnection.inc.php(238): DBConnection->__construct()
#6 /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php(175): DBConnection::getInstance()
#7 /var/www/html/classes/core/Application.inc.php(36): PKPApplication->__construct()
#8 /var/www/html/lib/pkp/includes/bootstrap. in /var/www/html/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php on line 456
[OJS Upgrade] Changing to installed on
sed: can't move '/var/www/html/config.inc.phpaEJDBJ' to '/var/www/html/config.inc.php': Resource busy
[OJS Upgrade] Upgrade is done, please restart the container.
```

I tried to change in file `/var/www/html/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php`, the function "mysql_" to "mysqli_", and run again and I got:

```
[OJS Upgrade] Changing to installed off
sed: can't move '/var/www/html/config.inc.phpHccKje' to '/var/www/html/config.inc.php': Resource busy
[OJS Upgrade] Upgrading...
<h1>Database connection failed!</h1>ojs2: Database connection failed!
[OJS Upgrade] Changing to installed on
sed: can't move '/var/www/html/config.inc.phpjdfOpc' to '/var/www/html/config.inc.php': Resource busy
[OJS Upgrade] Upgrade is done, please restart the container.
```

Here is my docker-compose.yml file:

```
version: '3.1'
  services:
    ojs:
      container_name: ojs
      image: pkpofficial/ojs:3_1_2-4
      restart: unless-stopped
      environment:
        SERVERNAME: localhost
        OJS_DB_HOST: 10.199.33.18
        OJS_DB_USER: revistas
        OJS_DB_PASSWORD: xxx
        OJS_DB_NAME: revistas
      ports:
        - "8080:80"
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./config.inc.php:/var/www/html/config.inc.php
        - /share/revistas/files:/var/www/files
        - /share/revistas/public:/var/www/html/public
```

Thanks.
